In [2]:
import numpy as np

In [3]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
b = np.array([[5.0, 6.0], [7.0, 8.0]])

soma = a + b
produto = a * b
diferenca = a - b
quociente = a / b
print("Soma")
print(soma)

print("produto")
print(produto)

print("diferença")
print(diferenca)

print("quociente")
print(quociente)

Soma
[[ 6.  8.]
 [10. 12.]]
produto
[[ 5. 12.]
 [21. 32.]]
diferença
[[-4. -4.]
 [-4. -4.]]
quociente
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [4]:
print("Resolvendo um sistema linear")
""""
    2x + 6y = 6
    5x + 3y = -9
    x = ? e y = ?
    Matriz de coeficientes e variáveis dependentes
    [2 6 = [6
    5 3 ] = -9]
"""

coef = np.array([[2,6], [5,3]])
vardeps = np.array([6, -9])
print(coef)
print(vardeps)

solucao = np.linalg.solve(coef, vardeps)
print(solucao)
print(f" X = {solucao[0]}")
print(f" Y = {solucao[1]}")

Resolvendo um sistema linear
[[2 6]
 [5 3]]
[ 6 -9]
[-3.  2.]
 X = -3.0
 Y = 2.0


# Exercício

In [15]:
print("resolvendo um sistema linear de 3 variáveis com Numpy")
""""
sistema linear x = euro, y = dolar e z = iene
2x + 5y + 2z = 18
5x + 3y + 4z = 25
3x + 3y + 4z = 19
x = ?
y = ?
z = ?
"""
coeficientes = np.array(
                [[2, 5, 2], 
                 [5, 3, 4], 
                 [3, 3, 4]]
                )

result = np.array([18, 25, 19])

solucao = np.linalg.solve(coeficientes, result)
print(solucao)
print(f" X = {solucao[0].round()}")
print(f" Y = {solucao[1].round()}")
print(f" Z = {solucao[2].round()}")


resolvendo um sistema linear de 3 variáveis com Numpy
[3. 2. 1.]
 X = 3.0
 Y = 2.0
 Z = 1.0
