In [4]:
import numpy as np

In [6]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
b = np.array([[5.0, 6.0], [7.0, 8.0]])

soma = a + b
produto = a * b
diferenca = a - b
quociente = a / b
print("Soma")
print(soma)

print("produto")
print(produto)

print("diferença")
print(diferenca)

print("quociente")
print(quociente)

Soma
[[ 6.  8.]
 [10. 12.]]
produto
[[ 5. 12.]
 [21. 32.]]
diferença
[[-4. -4.]
 [-4. -4.]]
quociente
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
